# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, default=30, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('experience', models.FloatField(blank=True, default=0.0, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('main_text', models.TextField(max_length=250)),
                ('stars', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books',
            name='review',
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'fiction'), ('NON_FICTION', 'non_fiction'), ('HORROR', 'horror'), ('EROTICA', 'erotica'), ('SELF_HELP', 'self_help')], default='FICTION', max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_favourite',
            field=models.BooleanField(default=False, verbose_name='Favourite'),
        ),
    ]
