# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180505_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=datetime.datetime(2018, 5, 6, 10, 30, 24, 142897, tzinfo=utc))),
                ('shelf_type', models.CharField(choices=[('READ', 'read'), ('WANT_TO_READ', 'want_to_read'), ('READING', 'reading')], default='WANT_TO_READ', max_length=20)),
            ],
            options={
                'verbose_name': 'Book Shelf',
                'verbose_name_plural': 'Book Shelves',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(default=datetime.datetime(2018, 5, 6, 10, 30, 24, 143509, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Favourite',
                'verbose_name_plural': 'Favourites',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('READ', 'read'), ('WANT_TO_READ', 'want_to_read'), ('CURRENTLY_READING', 'currently_reading')], default='WANT_TO_READ', max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('FICTION', 'fiction'), ('NON_FICTION', 'non_fiction'), ('HORROR', 'horror'), ('EROTICA', 'erotica'), ('SELF_HELP', 'self_help'), ('THRILLER', 'thriller')], default='FICTION', max_length=30),
        ),
        migrations.AddField(
            model_name='favourite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books'),
        ),
    ]
