# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180506_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.BookShelf'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 19, 32, 40, 29702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 19, 32, 40, 30417, tzinfo=utc)),
        ),
    ]
